trigger:
  branches:
    include:
    - master
    - refs/tags/*
  paths:
    include:
    - src/*
    - extra/*
    - CMakeLists.txt

pr: none
    
jobs:
  #- job: 'windows'
  #  displayName: 'Windows test'
  #  timeoutInMinutes: 120
  #  pool:
  #    vmImage: 'windows-latest' 
  #  steps:
  #    - checkout: self
  #      fetchDepth: 1
  #    - template: templates/windows.yml
  - job: 'linux'
        displayName: 'Ubuntu, Threads, CLI/GUI'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self
            fetchDepth: 1
          - template: templates/linux.yml