trigger:
  branches:
    include:
    - master
    - refs/tags/*
    
jobs:
- job: Windows
  pool:
    vmImage: 'vwindows-latest'
  steps:
  - template: templates/windows.yml
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: templates/linux.yml