trigger:
  branches:
    include:
    - master
    - refs/tags/*
  paths:
    include:
    - src/*
    - extra/*
    - CMakeLists.txt
    - templates/*

pr: none
    
jobs:
  - job: 'windows'
    displayName: 'Windows test'
    timeoutInMinutes: 120
    pool:
      vmImage: 'windows-latest' 
    steps:
      - checkout: self
        fetchDepth: 1
      - template: windows.yml