trigger: none

pr:
  autoCancel: true
  branches:
    include:
      - "*"
  paths:
    exclude:
    - .azure-pipelines/continuous.yml
    - .azure-pipelines/release.yml

jobs:
  - job: 'windows'
    displayName: 'Windows test'
    timeoutInMinutes: 120
    pool:
      vmImage: 'windows-latest' 
    steps:
      - checkout: self
        fetchDepth: 1
      - template: templates/windows.yml
      - template: templates/windows_package.yml
  
  - job: 'linux'
    displayName: 'Ubuntu Build'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - checkout: self
        fetchDepth: 1
      - template: templates/linux.yml
      - template: templates/linux_package.yml
  
  - job: 'osx'
    displayName: 'OSX Build'
    pool:
      vmImage: 'macos-latest'
    steps:
      - checkout: self
        fetchDepth: 1
      - template: templates/osx.yml
      - template: templates/osx_package.yml
